version: "3.7"
services:
  gm-tool:
    image: yby654/gm-tool:test
    container_name: gm-tool
    # command: npm start
    restart: unless-stopped
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
